=== nextcloud/build/resources/manifest.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:xa="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified" attributeFormDefault="unqualified">

	<!--
	xmllint lacks https support, rendering imports impossible unless hosting them
	somewhere without TLS enabled. The SVG xsd is not behind HTTPS, but it fails
	nevertheless, likely for a timeout since it does not load quickly.

	<xs:include schemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd" />
	<xs:import namespace="xsvg" schemaLocation="http://www.w3.org/TR/2002/WD-SVG11-20020108/SVG.xsd" />
	-->

	<xs:element name="buildapp">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metadata" type="metadata" minOccurs="1"
							maxOccurs="1"/>
				<xs:element name="appinfo" type="appinfo" minOccurs="1"
							maxOccurs="1"/>
				<xs:element name="structure" type="structure" minOccurs="1"
							maxOccurs="1"/>
				<xs:element name="view" type="view" minOccurs="1"
							maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="metadata">
		<xs:sequence>
			<xs:element name="version" type="version" minOccurs="1" maxOccurs="1"/>
			<xs:element name="created" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
			<xs:element name="last-modified" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="appinfo">
		<xs:sequence>
			<xs:element name="name" type="non-empty-string" minOccurs="1"
						maxOccurs="1"/>
			<!--<xs:element name="icon" type="svg" minOccurs="0"
						maxOccurs="1"/>-->
			<xs:element name="icon" type="non-empty-string" minOccurs="0"
						maxOccurs="1"/>
			<xs:element name="description" type="non-empty-string" minOccurs="1"
						maxOccurs="1"/>
			<xs:element name="version" type="version" minOccurs="1"
						maxOccurs="1"/>
			<xs:element name="uuid" type="non-empty-string" minOccurs="1"
						maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="structure">
		<xs:sequence>
			<!-- in future we might have multi-table apps, for now this is always one -->
			<xs:element name="table" type="table" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="view">
		<xs:sequence>
			<xs:element name="navigation" type="viewBasic" minOccurs="1" maxOccurs="1" />
			<xs:element name="detail" type="viewBasic" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="viewBasic">
		<xs:annotation>
			<xs:documentation>
				All tags will contain a reference to an existing column
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="headline" type="uuid" minOccurs="1" maxOccurs="1"/>
			<xs:element name="icon" type="uuid" minOccurs="0" maxOccurs="1"/>
			<xs:element name="subline" type="uuid" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="version">
		<xs:restriction base="limited-string">
			<xs:pattern value="[0-9]+(\.[0-9]+){0,2}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="limited-string">
		<xs:restriction base="non-empty-string">
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="non-empty-string">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="uuid">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="table">
		<xs:sequence>
			<xs:element name="uuid" type="uuid" minOccurs="1" maxOccurs="1" />
			<xs:element name="columns" type="columns" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="column">
		<xs:sequence>
			<xs:element name="uuid" type="uuid" minOccurs="1" maxOccurs="1" />
			<xs:element name="name" type="non-empty-string" minOccurs="1" maxOccurs="1" />
			<xs:element name="type" type="datatype" minOccurs="1" maxOccurs="1" />
			<xs:element name="required" type="xs:boolean" minOccurs="1" maxOccurs="1" />
			<xs:element name="default" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="choices" type="choices" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="columns">
		<xs:sequence>
			<xs:element name="column" type="column" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="choices">
		<xs:sequence>
			<xs:element name="option" type="non-empty-string" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="datatype-enumeration">
		<xs:restriction base="non-empty-string">
			<xs:enumeration value="checkbox"/>
			<xs:enumeration value="text"/>
			<xs:enumeration value="number"/>
			<xs:enumeration value="date"/>
			<xs:enumeration value="uri"/>
			<xs:enumeration value="contacts"/>
			<xs:enumeration value="users"/>
			<xs:enumeration value="file"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="datatype">
		<xs:simpleContent>
			<xs:extension base="datatype-enumeration">
				<xs:attribute name="limit" type="xs:integer" default="1" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== nextcloud/build/resources/reference-app.xml
<?xml version="1.0"?>
<buildapp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="./manifest.xsd">
	<metadata>
		<version>1.0.0</version>
		<created>2020-11-01T20:26:34+01:00</created>
		<last-modified>2020-11-01T22:13:30+01:00</last-modified>
	</metadata>
	<appinfo>
		<name>Software Test Management</name>
		<icon>PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93
			d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJtNy45MDYyIDFhNyA3IDAgMCAwLTYuOTA2MiA3
			IDcgNyAwIDAgMCA3IDcgNyA3IDAgMCAwIDctNyA3IDcgMCAwIDAtNy03IDcgNyAwIDAgMC0wLjA5
			Mzc1IDB6bTAuMDkzNzUgMi42OTkyYTQuMyA0LjMgMCAwIDEgNC4zMDA4IDQuMzAwOCA0LjMgNC4z
			IDAgMCAxLTQuMzAwOCA0LjMwMDggNC4zIDQuMyAwIDAgMS00LjMwMDgtNC4zMDA4IDQuMyA0LjMg
			MCAwIDEgNC4zMDA4LTQuMzAwOHoiIGZpbGw9IiNmZmYiIHN0cm9rZS1kYXNob2Zmc2V0PSIxMCIg
			c3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2Utd2lk
			dGg9Ii41IiBzdHlsZT0icGFpbnQtb3JkZXI6bWFya2VycyBzdHJva2UgZmlsbCIvPjwvc3ZnPgo=
		</icon>
		<description>Manages the test types and cases of software products</description>
		<version>1.0</version>
		<uuid>df0a9dc2-8d93-4e28-91b7-21a6a0e9ec86</uuid>
	</appinfo>
	<structure>
		<table>
			<uuid>942d02a8-2386-420c-a510-00a3807c3af7</uuid>
			<columns>
				<column>
					<uuid>676f0614-4306-42a9-b963-514624f1774d</uuid>
					<name>Product</name>
					<type>text</type>
					<required>true</required>
					<default/>
				</column>
				<column>
					<uuid>84979eeb-fb3c-4304-a28f-225d8cfd621e</uuid>
					<name>Icon</name>
					<type>file</type>
					<required>false</required>
					<default/>
				</column>
				<column>
					<uuid>0317e9e8-1b2c-4e36-958c-01429a0b98c8</uuid>
					<name>Maintainer</name>
					<type>contacts</type>
					<required>true</required>
					<default/>
					<max-values>2</max-values>
				</column>
				<column>
					<uuid>9f420efa-2d61-4682-adf7-d639d513348c</uuid>
					<name>State</name>
					<type>text</type>
					<required>true</required>
					<default/>
					<choices>
						<option>Not test</option>
						<option>testing</option>
						<option>Test failed</option>
						<option>Test succeeded</option>
					</choices>
				</column>
			</columns>
		</table>
	</structure>

	<view>
		<navigation>
			<type>list</type>
			<headline>
				<uuid>676f0614-4306-42a9-b963-514624f1774d</uuid>
				<type>text</type>
			</headline>
			<icon>
				<uuid>84979eeb-fb3c-4304-a28f-225d8cfd621e</uuid>
			</icon>
		</navigation>
		<detail>
			<type>avatar-header</type>
			<headline>
				<uuid>676f0614-4306-42a9-b963-514624f1774d</uuid>
				<type>text</type>
			</headline>
			<icon>
				<uuid>84979eeb-fb3c-4304-a28f-225d8cfd621e</uuid>
			</icon>
			<subline>
				<uuid>0317e9e8-1b2c-4e36-958c-01429a0b98c8</uuid>
				<type>displayname</type>
			</subline>
		</detail>
	</view>
</buildapp>
